common: &default_settings

#============================License key====================================

  license_key: '2bec573e0a007b6e5d11213de0d38a21cc30ffd'

  app_name: Le Ricette

  monitor_mode: true

  developer_mode: false

  log_level: info

#=============================Browser Monitoring ====================================

  browser_monitoring:

    auto_instrument: true


  audit_log:
    enabled: false

  capture_params: false

  transaction_tracer:

    enabled: true

    transaction_threshold: apdex_f

    record_sql: obfuscated

    stack_trace_threshold: 0.500

  error_collector:

    enabled: true

    capture_source: true

    ignore_errors: "ActionController::RoutingError"


#Application Environments

development:
  <<: *default_settings
  monitor_mode: false

  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: true

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
